# Generated by Django 3.1.7 on 2021-03-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210331_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugar',
            name='amout',
        ),
        migrations.AddField(
            model_name='sugar',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
