# Generated by Django 3.1.7 on 2021-04-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210331_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='sugar',
            name='type',
            field=models.CharField(choices=[('Lactose ', 'Lactose '), ('Glucose', 'Glucose'), ('Fructose', 'Fructose'), ('Sucrose', 'Sucrose')], default='Lactose ', max_length=8),
        ),
    ]
